# Data Cleaning Project using Python and Pandas

# Objective: Clean and prepare raw data for further analysis and machine learning.

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Load Dataset

In [3]:
df = pd.read_csv('DataAnalyst.csv' , encoding = 'latin1')

In [4]:
df

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,TRUE
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),Were looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
2249,2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1
2250,2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1
2251,2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1
2252,2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1

# Understand the Data

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           2253 non-null   int64
 1   Job  Title           2253 non-null   object
 2   Salary    Estimate   2253 non-null   object
 3   Job  Description     2253 non-null   object
 4   Rating               2253 non-null   float64
 5   Company   Name       2252 non-null   object
 6   Location             2253 non-null   object
 7   Headquarters         2253 non-null   object
 8   Size                 2253 non-null   object
 9   Founded              2253 non-null   int64
 10  Type  of  ownership  2253 non-null   object
 11  Industry             2253 non-null   object
 12  Sector               2253 non-null   object
 13  Revenue              2253 non-null   object
 14  Competitors          2253 non-null   object
 15  Easy  Apply          2253 non-null   object
dtypes: float64(1), int64(2), object(13)
memory usage: 281.8+ KB

In [6]:
df.shape

(2253, 16)

In [7]:
df.describe()

       Unnamed: 0       Rating      Founded
count   2253.0000  2253.000000  2253.000000
mean    1126.0000     3.160630  1398.522858
std      650.5294     1.665228   901.929251
min        0.0000    -1.000000    -1.000000
25%      563.0000     3.100000    -1.000000
50%     1126.0000     3.600000  1979.000000
75%     1689.0000     4.000000  2002.000000
max     2252.0000     5.000000  2019.000000

# Removing Unnecessary columns

In [8]:
df = df.drop(columns = 'Unnamed: 0')

# Check Missing Values

In [9]:
df.isnull().sum()

Job  Title             0
Salary    Estimate     0
Job  Description       0
Rating                 0
Company   Name         1
Location               0
Headquarters           0
Size                   0
Founded                0
Type  of  ownership    0
Industry               0
Sector                 0
Revenue                0
Competitors            0
Easy  Apply            0
dtype: int64

In [6]:
#There is a null in the company column
#Further will impute it

# Check Duplicates

In [10]:
df.duplicated().sum()

0

# COLUMN NAME String Cleaning

In [12]:
df.columns

Index(['Job  Title', 'Salary    Estimate', 'Job  Description', 'Rating',
       'Company   Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type  of  ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy  Apply'],
      dtype='object')

In [13]:
#There are spaces in between the texts

In [14]:
# .str.strip() only removes spaces from begining and end

In [15]:
df.columns = df.columns.str.strip()

In [16]:
df.columns = df.columns.str.replace(' ','_')

In [17]:
df.columns

Index(['Job__Title', 'Salary____Estimate', 'Job__Description', 'Rating',
       'Company___Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type__of__ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy__Apply'],
      dtype='object')

In [18]:
# check if there is an empty string

In [19]:
(df == '').sum()

Job__Title             0
Salary____Estimate     0
Job__Description       0
Rating                 0
Company___Name         0
Location               0
Headquarters           0
Size                   0
Founded                0
Type__of__ownership    0
Industry               0
Sector                 0
Revenue                0
Competitors            0
Easy__Apply            0
dtype: int64

In [20]:
(df == '-1').sum()

Job__Title                0
Salary____Estimate        1
Job__Description          0
Rating                    0
Company___Name            0
Location                  0
Headquarters            172
Size                    163
Founded                   0
Type__of__ownership     163
Industry                353
Sector                  353
Revenue                 163
Competitors            1732
Easy__Apply            2173
dtype: int64

In [21]:
(df == -1).sum()

Job__Title               0
Salary____Estimate       0
Job__Description         0
Rating                 272
Company___Name           0
Location                 0
Headquarters             0
Size                     0
Founded                660
Type__of__ownership      0
Industry                 0
Sector                   0
Revenue                  0
Competitors              0
Easy__Apply              0
dtype: int64

# Check unique of object type columns

In [26]:
obj_col = df.select_dtypes(include=['object']).columns.to_list()
print(obj_col)

['Job__Title', 'Salary____Estimate', 'Job__Description', 'Company___Name', 'Location', 'Headquarters', 'Size', 'Type__of__ownership', 'Industry', 'Sector', 'Revenue', 'Competitors', 'Easy__Apply']

In [27]:
for col in obj_col:
    u = df[col].unique()[:5] 
    print(col)
    print(u)
    print('==' * 40)

Job__Title
['Data Analyst, Center on Immigration and Justice (CIJ)'
 'Quality Data Analyst'
 'Senior Data Analyst, Insights & Analytics Team [Customer Operations]'
 'Data Analyst' 'Reporting Data Analyst']
================================================================================
Salary____Estimate
['$37K-$66K (Glassdoor est.)' '$46K-$87K (Glassdoor est.)'
 '$51K-$88K (Glassdoor est.)' '$51K-$87K (Glassdoor est.)'
 '$59K-$85K (Glassdoor est.)']
================================================================================
Job__Description
["Are you eager to roll up your sleeves and harness data to drive policy change? Do you enjoy sifting through complex datasets to illuminate trends and insights? Do you see yourself working for a values-driven organization with a vision to tackle the most pressing injustices of our day?\n\nWe are looking to hire a bright, hard-working, and creative individual with strong data management skills and a demonstrated commitment to immigrant's rights. The Data Analyst will assist with analysis and reporting needs for Veras Center on Immigration and Justice (CIJ), working across its current projects and future Vera initiatives.\n\nWho we are:\n\nFounded in 1961, The Vera Institute is an independent, non-partisan, nonprofit organization that combines expertise in research, technical assistance, and demonstration projects to assist leaders in government and civil society examine justice policy and practice, and improve the systems people rely on for justice and safety.\nWe study problems that impede human dignity and justice.\nWe pilot solutions that are at once transformative and achievable.\nWe engage diverse communities in informed debate.\nAnd we harness the power of evidence to drive effective policy and practice\nWhat were doing:\n\nWe are helping to build a movementamong government leaders, advocates, and the immigration legal services communitytowards universal legal representation for immigrants facing deportation. In the face of stepped-up immigration enforcement, millions of non-citizens are at risk of extended detention and permanent separation from their families and communities. Veras Center on Immigration and Justice (CIJ) partners with government, non-profit partners, and communities to improve government systems that affect immigrants and their families. CIJ administers several nationwide legal services programs for immigrants facing deportation, develops and implements pilot programs, provides technical assistance, and conducts independent research and evaluation.\n\nThats where you come in:\nThe Data Analyst will support the Centers programmatic efforts through regular monitoring and reporting of federal government and subcontractor data. CIJ manages several proprietary databases that run on AWS and Caspio and uses SQL, R, and Python to manage data. This is an opportunity to help shape an innovative national research and policy agenda as part of a dedicated team of experts working to improve access to justice for non-citizens.\n\nVera seeks to hire a Data Analyst to work on various data management projects with its Center on Immigration and Justice (CIJ). In collaboration with other Data Analysts, this position will involve work across several projects, such as the Unaccompanied Childrens Program (UCP), a program to increase legal representation for immigrant children facing deportation without a parent or legal guardian. The position may cover additional duties for the Legal Orientation Program for Custodians (LOPC), which educates the custodians of unaccompanied children about their rights and the immigration court process.\n\nAbout the role:\n\nAs a Data Analyst, you will report to a member of the research team and work in close collaboration with other Vera staff on ongoing database management, monitoring, reporting, and analysis projects. Youll support the team by taking ownership of ongoing monitoring and reporting tasks involving large data sets. Other principal responsibilities will include:\nSupporting research staff by preparing large datasets for analysis, including merging, cleaning, and recoding data;\nProviding insights into program performance through summary statistics and performance indicators;\nProducing timely reports on Vera projects for team members and stakeholders;\nImproving recurring reporting processes by optimizing code and producing subsequent documentation;\nCoordinating database management tasks such as participating in new database design, modifying existing databases, and communicating with outside engineers and subcontractors;\nDeveloping codebooks and delivering user trainings through webinars and database guides;\nBuilding and maintaining interactive dashboards;\nDocumenting and correcting data quality issues;\nWorking with supervisors to prioritize program needs;\nAssisting on other projects and tasks as assigned.\nAbout you:\n\nYoure committed to improving issues affecting immigrants in the United States. Applicants with personal experiences with the immigration system are especially encouraged to apply.\n\nYoure just getting started in your career and have 1 2 years of professional or internship experience working with large datasets and preparing data for analysis.\n\nYou have a real enthusiasm for working with data.\n\nYou are comfortable writing queries in SQL, R, and/or Python, or have a solid foundation coding in other programming languages used to manipulate data. Experience working collaboratively using tools like Git/GitHub is a plus.\n\nYou have exceptional attention to detail, strong problem-solving ability and logical reasoning skills, and the ability to detect anomalies in data.\n\nYoure able to work on multiple projects effectively and efficiently, both independently and collaboratively with a team.\n\nThis position involves working with secure data that may require government security clearance. That clearance is restricted to U.S. citizens and citizens of countries that are party to collective defense agreements with the U.S. The list of those countries is detailed on this webpage. An additional requirement of that clearance is residence in the United States for at least three of the last five years.\n\nHow to apply:\n\nPlease submit cover letter and resume. Applications will be considered on a rolling basis until position is filled. Online submission in PDF format is preferred. Applications with no cover letter attached will not be considered. The cover letter should address your interest in CIJ and this position.\n\nHowever, if necessary, materials may be mailed or faxed to\n\nATTN: Human Resources / CIJ Data Analyst Recruitment\n\nVera Institute of Justice\n\n34 35th St, Suite 4-2A\n\nBrooklyn, NY 11232\n\nFax: (212) 941-9407\n\nPlease use only one method (online, mail or fax) of submission.\n\nNo phone calls, please. Only applicants selected for interviews will be contacted.\n\nVera is an equal opportunity/affirmative action employer. All qualified applicants will be considered for employment without unlawful discrimination based on race, color, creed, national origin, sex, age, disability, marital status, sexual orientation, military status, prior record of arrest or conviction, citizenship status, current employment status, or caregiver status.\n\nVera works to advance justice, particularly racial justice, in an increasingly multicultural country and globally connected world. We value diverse experiences, including with regard to educational background and justice system contact, and depend on a diverse staff to carry out our mission.\n\nFor more information about Vera and CIJs work, please visit www.vera.org.\n\nPowered by JazzHR"
 'Overview\n\nProvides analytical and technical support for the integration of multiple data sources used to prepare internal and external reporting for the Quality Management team and business stakeholders. Provides support and analytical insight for Quality Incentive measures, HEDIS measures, and Quality Improvement initiatives. Monitors, analyzes, and communicates Quality performance related to benchmarks. Collaborates with clinical and operational teams within Quality Management, as well as with CHOICE Clinical Operations and Business Intelligence & Analytics (BIA). Participates in data validation of current reporting and dashboards. Monitors data integrity of databases and provides recommendation accordingly. Participates in the development of internal dashboards and databases. Works under general direction.\n\nResponsibilities\nProvides support and analytical insight for Quality Incentive measures, HEDIS measures, and Quality Improvement initiatives.\nMonitors internal performance against benchmarks through analysis.\nParticipates in the identification, development, management, and monitoring of quality improvement initiatives.\nCollaborates with Education staff and makes recommendations for areas of focus in training of assessors and care managers, based on analysis of performance trends.\nResearches and identifies technical/operational problems surrounding systems/applications; communicates/refers complex and unresolved problems to management, Business Intelligence & Analytics (BIA), and/or IT.\nConducts ad hoc analyses to help identify operational gaps in care; drafts presentations, reports, publications, etc. regarding results of analyses.\nCommunicates results of data analysis to non-technical audiences.\nParticipates in prioritization of departmental goals based on identification of operational gaps in care.\nParticipates in establishing data quality specifications and designs. Coordinates and supports integrated data systems for analyzing and validating information.\nIdentifies and makes recommendations for reporting re-designs and platforms for reporting (e.g. automating a manual Excel file using macros, developing a MicroStrategy dashboard to replace manually updated Excel dashboards, moving data storage from Excel to Access, etc.), as needed. Trains staff on use of new/updated systems and related topics.\nAssists Quality management team with database and department reports. Conducts operations review and analysis of processes and procedures, issues report of findings and implements approved changes as required.\nIdentifies and recommends software needs and applications to accomplish required reporting.\nRetrieves, compiles, reviews and ensures accuracy of data from databases; researches and corrects discrepancies, as needed. Analyzes data from internal and external sources. Identifies and resolves data quality issues before reports are generated. Works with staff to correct data entry errors.\nAnalyzes data, identifies trends, reoccurring problems, statistically significant findings and prepares reports/summaries for management review.\nActs as a liaison between Quality Management, CHOICE Clinical Operations, and BIA.\nReviews and identifies trends and variances in data and reports. Researches findings and determines appropriateness of elevating identified issues to leadership for further review/evaluation/action.\nMonitors and maintains files by ensuring that files are current and of relevant nature.\nAnalyzes and corrects error reports to ensure timely and accurate data; develops corrective actions to prevent errors where possible.\nParticipates in special projects and performs other duties, as needed.\nQualifications\nEducation: Bachelors degree in bio/statistics, epidemiology, mathematics, computer science, social sciences, a related field or the equivalent work experience required. Masters degree with concentration in computer science, data science, or statistics preferred.\n\n\nExperience: Minimum of two years experience performing increasingly complex data analysis and interpretation, preferably in a managed care or health care setting, required. Experience with data extraction and manipulation required. Experience with relational databases and programming experience in SQL or PL/SQL required. Experience with claims data and health plan quality metrics (e.g., HEDIS, QARR) preferred. Proficiency conducting statistical analysis with R, SAS, Stata or other statistical software preferred. Advanced personal computer skills, including Microsoft Word, PowerPoint, Excel, and Access required. Effective oral, written communication and interpersonal skills required. Ability to multi task in a fast-paced environment required.\n\nCA2020'
 'We\x92re looking for a Senior Data Analyst who has a love of mentorship, data visualization, and generating actionable insights from raw data. In this role, you\x92ll have the opportunity to be an organizational influencer, who will generate insights with a good degree of autonomy, and partner with data science to grow deeper analytical skills. You will be joining the Insights & Analytics team, a team tasked with developing insights and reporting to support our customers and advisors\x92 needs. This team sits within the Customer Operations team, but is also connected to the Product organization.\n\nIn this role, you will work mainly with Customer Operations stakeholders to set KPIs and evaluate the effectiveness of current strategies and workflows. You will be involved in many aspects of data operations, from data auditing to building dashboards and analytical insights. For example, you will review the code of more junior analysts and organize coding workshops. You will build metrics to evaluate the performance of our advisors, eliminating confounding variables and creating weighted measures that account for individual success. You will define metrics and create dashboards to track the success of the current strategic direction. You will analyze the text-based interactions with our advisors to improve care quality. You will also analyze interactions with our chatbot to improve the responses of the bot to match customer expectations. You will collaborate with the Data Engineering team in pursuit of better data modeling and you can collaborate with the Data Science team on more modeling-heavy pursuits, like topic modeling or search recommendations. You will be a mentor to all other members of the analytics team, which demands that you excel in a culture of teaching and learning.\n\nYou will report to the Manager of the Insights & Analytics team, Customer Operations in Squarespace\x92s New York offices.\n\nRESPONSIBILITIES\nDesign and develop KPIs, reports, and dashboards using BI/data visualization tools that clearly track the effectiveness of current strategies\nExecute and communicate impactful analyses, using SQL and R/Python to improve the customer experience and drive Customer Operations and Product roadmap\nRaise the skill level of the analytics team through reviewing code, organizing training sessions, acting as a mentor, and introducing new analytical methods and tools\nHelp design and evaluate experiments and pilots, setting clear hypotheses and success metrics, as well as using the right statistical methods for analyses\nEffectively partner with Customer Operations and Product stakeholders, as well as our Data Engineering team\nQUALIFICATIONS\n4 or more years of experience as a data analyst, data scientist, or in a relevant field in which you have worked with large datasets to transform data to meaningful insights\nMastery of SQL, and experience with R/Python\nExperience with dashboarding/BI tools like Chartio, Looker, Tableau\nExperience with data cleaning, analysis, and presentation to non-technical stakeholders\nBachelor\x92s degree in a quantitative or logic-driven discipline\nIntellectual curiosity and a deep love of mentorship and generating actionable insights\nPreferred: Advanced degree (Master\x92s or PhD) in quantitative field\nPreferred: Experience with topic modeling, text analytics/natural language processing\nWe are hiring at various experience levels and we\x92re particularly interested in having a diverse team with a broad set of skills and viewpoints. If this seems like an opportunity you\x92d like to explore, but you\x92re not sure if you qualify, we encourage you to apply anyway!\n\nAbout Squarespace\n\nSquarespace makes beautiful products to help people with creative ideas succeed. By blending elegant design and sophisticated engineering, we empower millions of people \x97 from individuals and local artists to entrepreneurs shaping the world\x92s most iconic businesses \x97 to share their stories with the world. Squarespace\x92s team of more than 900 is headquartered in downtown New York City, with offices in Dublin and Portland. For more information, visit www.squarespace.com/about.\n\nToday, more than a million people around the globe use Squarespace to share different perspectives and experiences with the world. Not only do we embrace and celebrate the diversity of our customer base, but we also strive for the same in our employees. At Squarespace, we are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender, gender identity or expression, or veteran status. We are proud to be an equal opportunity workplace.'

In [31]:
# There is an issue with most of the columns above

In [29]:
int_col = df.select_dtypes(include = ['int64', 'float64']).columns.to_list()
print(int_col)

['Rating', 'Founded']

In [30]:
for col in int_col:
    u = df[col].unique()[:5] 
    print(col)
    print(u)
    print('==' * 40)

Rating
[3.2 3.8 3.4 4.1 3.9]
================================================================================
Founded
[1961 1893 2003 2002 2009]
================================================================================

In [ ]:
# 'Rating' and 'Founded' are in proper format

# First replacing the '-1' and 1 with Nulls

In [32]:
df = df.replace(['-1' , -1] , pd.NA)

In [33]:
#(df == '-1').sum() and (df == -1).sum() cross verify

In [34]:
df.isnull().sum()

Job__Title                0
Salary____Estimate        1
Job__Description          0
Rating                  272
Company___Name            1
Location                  0
Headquarters            172
Size                    163
Founded                 660
Type__of__ownership     163
Industry                353
Sector                  353
Revenue                 163
Competitors            1732
Easy__Apply            2173
dtype: int64

In [36]:
# checking info() because we replaced all values

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Job__Title           2253 non-null   object
 1   Salary____Estimate   2252 non-null   object
 2   Job__Description     2253 non-null   object
 3   Rating               1981 non-null   object
 4   Company___Name       2252 non-null   object
 5   Location             2253 non-null   object
 6   Headquarters         2081 non-null   object
 7   Size                 2090 non-null   object
 8   Founded              1593 non-null   object
 9   Type__of__ownership  2090 non-null   object
 10  Industry             1900 non-null   object
 11  Sector               1900 non-null   object
 12  Revenue              2090 non-null   object
 13  Competitors          521 non-null    object
 14  Easy__Apply          80 non-null     object
dtypes: object(15)
memory usage: 264.1+ KB

# IMPUTATION OF THE NULLS

In [37]:
# fill rating nulls

In [38]:
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

/var/folders/fy/9b620qvx0vv5wfcppkyf_06h0000gn/T/ipykernel_25385/1504320987.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [39]:
# keep founded as null

# Change the data type back to Numeric

In [40]:
df['Rating'] = pd.to_numeric(df['Rating'])

In [41]:
# change data type for Founded col (using 'Int64' because it has nulls)

In [42]:
df['Founded'] = df['Founded'].astype('Int64')

# IMPUTATION (Object col)

In [ ]:
# 'Easy__Apply'

In [44]:
df['Easy__Apply'].unique()

array(['TRUE', <NA>], dtype=object)

In [45]:
df['Easy__Apply'] = df['Easy__Apply'].fillna('FALSE')

In [46]:
# 'Revenue'

In [48]:
#Revenue
#['$100 to $500 million (USD)' '$2 to $5 billion (USD)'
# 'Unknown / Non-Applicable' '$50 to $100 million (USD)'
 #'$1 to $2 billion (USD)']
# filling nulls with a 'Unknown / Non-Applicable' already available

In [49]:
df['Revenue'] = df['Revenue'].fillna('Unknown / Non-Applicable')

In [50]:
#FOR Competitors, Sector ,Industry ,Type__of__ownership ,Size, Headquarters cols
# filling nulls with 'Unknown' rather than using mode

In [51]:
text_cols = ['Competitors', 'Sector', 'Industry', 
             'Type__of__ownership', 'Headquarters', 'Size']

In [52]:
df[text_cols] = df[text_cols].fillna('Unknown')

In [54]:
# check null count

In [55]:
df.isnull().sum()

Job__Title               0
Salary____Estimate       1
Job__Description         0
Rating                   0
Company___Name           1
Location                 0
Headquarters             0
Size                     0
Founded                660
Type__of__ownership      0
Industry                 0
Sector                   0
Revenue                  0
Competitors              0
Easy__Apply              0
dtype: int64

In [56]:
df[['Company___Name', 'Salary____Estimate']].isna().sum()

Company___Name        1
Salary____Estimate    1
dtype: int64

In [57]:
df[df[['Company___Name', 'Salary____Estimate']].isna().any(axis=1)]

,Job__Title,Salary____Estimate,Job__Description,Rating,Company___Name,Location,Headquarters,Size,Founded,Type__of__ownership,Industry,Sector,Revenue,Competitors,Easy__Apply
1860,Data Analyst,$53K-$99K (Glassdoor est.),"Kindred at Home, part of the Kindred at Home f...",3.7,NaN,"Mooresville, NC",Unknown,Unknown,<NA>,Unknown,Unknown,Unknown,Unknown / Non-Applicable,Unknown,FALSE
2149,Configuration/Data Management Analyst III,<NA>,Job Description\nPosition Title: Configuration...,4.4,Protingent\n4.4,"Kent, WA","Bellevue, WA",51 to 200 employees,2001,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),Unknown,FALSE

In [58]:
# deleting rows beacuse its a very less count of nulls

In [59]:
df = df.dropna(subset = ['Company___Name', 'Salary____Estimate']  , how = 'any')

In [60]:
#again that line of code run
df[df[['Company___Name', 'Salary____Estimate']].isna().any(axis=1)]

Empty DataFrame
Columns: [Job__Title, Salary____Estimate, Job__Description, Rating, Company___Name, Location, Headquarters, Size, Founded, Type__of__ownership, Industry, Sector, Revenue, Competitors, Easy__Apply]
Index: []

In [62]:
#final check
df.isnull().sum()

Job__Title               0
Salary____Estimate       0
Job__Description         0
Rating                   0
Company___Name           0
Location                 0
Headquarters             0
Size                     0
Founded                659
Type__of__ownership      0
Industry                 0
Sector                   0
Revenue                  0
Competitors              0
Easy__Apply              0
dtype: int64

In [63]:
#final check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2251 entries, 0 to 2252
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Job__Title           2251 non-null   object
 1   Salary____Estimate   2251 non-null   object
 2   Job__Description     2251 non-null   object
 3   Rating               2251 non-null   float64
 4   Company___Name       2251 non-null   object
 5   Location             2251 non-null   object
 6   Headquarters         2251 non-null   object
 7   Size                 2251 non-null   object
 8   Founded              1592 non-null   Int64
 9   Type__of__ownership  2251 non-null   object
 10  Industry             2251 non-null   object
 11  Sector               2251 non-null   object
 12  Revenue              2251 non-null   object
 13  Competitors          2251 non-null   object
 14  Easy__Apply          2251 non-null   object
dtypes: Int64(1), float64(1), object(13)
memory usage: 283.6+ KB

In [64]:
#verifying -1 and '-1'

In [65]:
for col in df.columns:
    count = ((df[col] == '-1') | (df[col] == -1)).sum()
    if count > 0:
        print(col)

# Cleaning the 'Salary____Estimate' column

In [66]:
# salary column:
#important
#37k - 	66K (Glassdoor est.) ----remove (Glassdoor est.)
#remove $

In [67]:
df['Salary____Estimate']

0        $37K-$66K (Glassdoor est.)
1        $37K-$66K (Glassdoor est.)
2        $37K-$66K (Glassdoor est.)
3        $37K-$66K (Glassdoor est.)
4        $37K-$66K (Glassdoor est.)
                   ...
2248    $78K-$104K (Glassdoor est.)
2249    $78K-$104K (Glassdoor est.)
2250    $78K-$104K (Glassdoor est.)
2251    $78K-$104K (Glassdoor est.)
2252    $78K-$104K (Glassdoor est.)
Name: Salary____Estimate, Length: 2251, dtype: object

In [68]:
# removing the character part of the column
df['Salary____Estimate'] = df['Salary____Estimate'].str.replace(r'\(.*?\)', '', regex=True)

In [70]:
# replace / remove the dollar symbol
df['Salary____Estimate'] = df['Salary____Estimate'].str.replace('$','')

In [72]:
# filling /replacing the 'K' with 000
df['Salary____Estimate'] = df['Salary____Estimate'].str.replace('K', '000')

In [73]:
#verify
df['Salary____Estimate']

0        37000-66000
1        37000-66000
2        37000-66000
3        37000-66000
4        37000-66000
            ...
2248    78000-104000
2249    78000-104000
2250    78000-104000
2251    78000-104000
2252    78000-104000
Name: Salary____Estimate, Length: 2251, dtype: object

In [74]:
#-- salary column
#....37000-66000 getting a acutal salary number out of this range
#...coversion of it from object to numeric
#....normalise the value to avg

In [75]:
df[['min','max']] = df['Salary____Estimate'].str.split('-', expand=True)

In [76]:
df.head(1)

,Job__Title,Salary____Estimate,Job__Description,Rating,Company___Name,Location,Headquarters,Size,Founded,Type__of__ownership,Industry,Sector,Revenue,Competitors,Easy__Apply,min,max
0,"Data Analyst, Center on Immigration and Justic...",37000-66000,Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),Unknown,TRUE,37000,66000

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2251 entries, 0 to 2252
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Job__Title           2251 non-null   object
 1   Salary____Estimate   2251 non-null   object
 2   Job__Description     2251 non-null   object
 3   Rating               2251 non-null   float64
 4   Company___Name       2251 non-null   object
 5   Location             2251 non-null   object
 6   Headquarters         2251 non-null   object
 7   Size                 2251 non-null   object
 8   Founded              1592 non-null   Int64
 9   Type__of__ownership  2251 non-null   object
 10  Industry             2251 non-null   object
 11  Sector               2251 non-null   object
 12  Revenue              2251 non-null   object
 13  Competitors          2251 non-null   object
 14  Easy__Apply          2251 non-null   object
 15  min                  2251 non-null   object
 16  max                  2251 non-null   object
dtypes: Int64(1), float64(1), object(15)
memory usage: 318.7+ KB

In [78]:
# change min max columns into int for getting salary calculations

In [81]:
df['min'] = pd.to_numeric(df['min'])

In [82]:
df['max'] = pd.to_numeric(df['max'])

In [ ]:
#

In [83]:
df['salary_cal'] = (df['min'] + df['max']) / 2

In [84]:
df['salary_cal']

0       51500.0
1       51500.0
2       51500.0
3       51500.0
4       51500.0
         ...
2248    91000.0
2249    91000.0
2250    91000.0
2251    91000.0
2252    91000.0
Name: salary_cal, Length: 2251, dtype: float64

# remove the min max columns

In [85]:
df= df.drop(columns = ['min','max'])

# Validation Checks

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2251 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Job__Title           2251 non-null   object
 1   Salary____Estimate   2251 non-null   object
 2   Job__Description     2251 non-null   object
 3   Rating               2251 non-null   float64
 4   Company___Name       2251 non-null   object
 5   Location             2251 non-null   object
 6   Headquarters         2251 non-null   object
 7   Size                 2251 non-null   object
 8   Founded              1592 non-null   Int64
 9   Type__of__ownership  2251 non-null   object
 10  Industry             2251 non-null   object
 11  Sector               2251 non-null   object
 12  Revenue              2251 non-null   object
 13  Competitors          2251 non-null   object
 14  Easy__Apply          2251 non-null   object
 15  salary_cal           2251 non-null   float64
dtypes: Int64(1), float64(2), object(13)
memory usage: 301.2+ KB

In [88]:
df.isnull().sum()

Job__Title               0
Salary____Estimate       0
Job__Description         0
Rating                   0
Company___Name           0
Location                 0
Headquarters             0
Size                     0
Founded                659
Type__of__ownership      0
Industry                 0
Sector                   0
Revenue                  0
Competitors              0
Easy__Apply              0
salary_cal               0
dtype: int64

# Export Cleaned Data

In [89]:
df.to_csv('cleaned_git_data.csv' ,index = False ,encoding = 'utf-8')